version: "2"

exclude_patterns:
- ".github/"
- ".idea/"
- ".mvn/"
- "javadoc/"
- "target/"
- "utils/"

plugins:
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
      enabled: true
      channel: "beta"
  sonar-java:
      enabled: true
      config:
        sonar.java.source: "7"
        minimum_severity: critical
  editorconfig:
      enabled: true
      channel: beta
  fixme:
      enabled: true
  git-legal:
      enabled: true
  markdownlint:
      enabled: true