version: "2"

exclude_patterns:
- ".github/"
- ".idea/"
- ".mvn/"
- "javadoc/"
- "target/"
- "utils/"
- ".circleci"

plugins:
  pmd:
    enabled: true
    channel: "beta"
  sonar-java:
      enabled: true
      config:
        sonar.java.source: "11"
        minimum_severity: minor
      tests_patterns:
          - src/test/**

  editorconfig:
      enabled: true
      channel: beta
  markdownlint:
      enabled: true