version: "2"

exclude_patterns:
- ".github/"
- ".idea/"
- ".mvn/"
- "javadoc/"
- "target/"
- "utils/"

plugins:
  checkstyle:
    enabled: true
  pmd:
    enabled: true
  findbugs:
    enabled: true
  junit:
    enabled: true
  jacoco:
    enabled: true