version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/maven:3.9.0-jdk-19.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
workflows:
  version: 2
  build:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
          triggers:
            - schedule:
                cron: "0 */3 * * *"