version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/maven:3.9.0-jdk-19.0.2
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
workflows:
  test_utilities:
    jobs:
      - build-and-test