version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
workflows:
  test_utilities:
    jobs:
      - build-and-test