version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1
  maven: circleci/maven@1.4.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean install
  sonarcloud:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run:
          name: SonarCloud
          command: sonarcloud/scan
workflows:
  main:
    jobs:
      - build
      - maven/test
      - sonarcloud