version: 2.1

jobs:
  build-and-test:
    docker:
      - image: maven:3.8.1-openjdk-19.0.2-slim
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
          triggers:
workflows:
  test_utilities:
    jobs:
      - build-and-test