version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean install
  test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test
  sonarcloud:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run:
          name: SonarCloud
          command: mvn -e verify sonar:sonar -Dsonar.projectKey=acrastt_Utils

workflows:
  main:
    jobs:
      - build
      - test
      - sonarcloud